// <auto-generated />
namespace LectureWebPrgBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ThisOneIsTheOne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThisOneIsTheOne));
        
        string IMigrationMetadata.Id
        {
            get { return "202106131303325_ThisOneIsTheOne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
